# Generated by Django 5.0.3 on 2024-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_organization_organization_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(related_name='events', to='myapp.organization'),
        ),
    ]
